"""Column in our users table that stores our passwords

Revision ID: 19bdca5d5f46
Revises: 6f47a5e70c60
Create Date: 2022-02-02 16:57:04.110913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bdca5d5f46'
down_revision = '6f47a5e70c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
