"""added email

Revision ID: 61be8723b0ea
Revises: 19bdca5d5f46
Create Date: 2022-02-02 19:51:41.506023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61be8723b0ea'
down_revision = '19bdca5d5f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
